modLoader="javafml"
loaderVersion="[43,)"
license="GNU GPLv3"
[[mods]]
modId="prevmm"
version="0.1.0-1.19.2"
displayName="Prev's Magnificent Materials"
updateJSONURL="https://github.com/minecraft-prev/Magnificent-Materials"
displayURL="https://github.com/minecraft-prev/Magnificent-Materials"
logoFile="banner.png"
credits="Forge Developers & Contributers + Mojang & Minecraft + My Cats"
authors="prev"

# Display Test controls the display for your mod in the server connection screen
# MATCH_VERSION, IGNORE_SERVER_VERSION, IGNORE_ALL_VERSION
displayTest="MATCH_VERSION"

description="Adding many new materials with quality art and all the expected features to Minecraft."

# A list of dependencies for this mod - use the. to indicate dependency for a specific mod.
[[dependencies.prevmm]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.prevmm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"
